#!/usr/bin/env python
import sys
import select

# check to see if we have any data passed to stdin
if select.select([sys.stdin,],[],[],0.0)[0]:
  print "\n"
  print repr(sys.stdin.read()).strip('\'')[:-2]
  print "\n"
else:
  print "No data passed to stdin. Please try again."

